# Generated by Django 2.2.1 on 2019-07-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='requestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=15)),
                ('Middle_Name', models.CharField(max_length=15)),
                ('Last_Name', models.CharField(max_length=15)),
                ('Doctor_Name', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=50)),
                ('Time', models.CharField(max_length=20)),
            ],
        ),
    ]
