---
title: "Medico"
output: 
  flexdashboard::flex_dashboard:
    logo: logo.png
    theme: bootstrap
    orientation: rows
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
library(flexdashboard)
source("script/mapping.R")
source("script/gen_chart.R")
source("script/pop_chart.R")
source("script/per_house_chart.R")
source("script/pie_chart.R")
```

Total {data-navmenu="Population"}
=====================================

Row
-------------------------------------
    
### Nepal Provincial Map
    
```{r echo=FALSE}
create_map(df_address = "data/processed/population/00_totaldf.csv", column1 = "no_of_cases_identified",column2 = "no_of_cases_reported")
```
 
### Population distribution
    
```{r}
create_pie(df_address = "data/processed/population/pop_distri.csv")
``` 

Row
-------------------------------------
    
### HouseHold & Population
    
```{r}
create_pop_chart(df_address = "data/processed/population/00_totaldf.csv")
``` 
    
### Gender Distribution

```{r}
create_gen_chart(df_address = "data/processed/population/00_totaldf.csv")
```


Metropoltian {data-navmenu="Population"}
=====================================

Row
-------------------------------------
    
### Metropolitian Population Distribution Choloropelth
    
```{r}
create_map(df_address = "data/processed/population/01_metropolitian.csv", column1 = "no. of cases identified",column2 = "no. of cases reported",bins = c(45, 161, 106,78, 159, 164, 91, Inf))
```
 
### HouseHold & Population
    
```{r}
create_pop_chart(df_address = "data/processed/population/01_metropolitian.csv")
``` 

Row
-------------------------------------
    
### People Per House
    
```{r}
create_per_house(df_address = "data/processed/population/01_metropolitian.csv")
```
    
### Gender Distribution

```{r}
create_gen_chart(df_address = "data/processed/population/01_metropolitian.csv")
```


Sub-metropolitian {data-navmenu="Options"}
=====================================

Row
-------------------------------------
    
### Sub- metropolitian Population  Choropleth
    
```{r}
create_map(df_address = "data/processed/population/02_submetropolitian.csv", column1 = "household",column2 = "population",bins = c(45, 161, 106,78, 159, 164, 91, Inf))
```
 
### HouseHold & Population
    
```{r}
create_pop_chart(df_address = "data/processed/population/02_submetropolitian.csv")
``` 

Row
-------------------------------------
    
### People Per House
    
```{r}
create_per_house(df_address = "data/processed/population/02_submetropolitian.csv")
```
    
### Gender Distribution

```{r}
create_gen_chart(df_address = "data/processed/population/02_submetropolitian.csv")
```



Muncipality {data-navmenu="Population"}
=====================================

Row
-------------------------------------
    
### Muncipality Population  Choropleth
    
```{r}
create_map(df_address = "data/processed/population/03_muncipality.csv", column1 = "household",column2 = "population",bins = c(45, 161, 106,78, 159, 164, 91, Inf))
```
 
### HouseHold & Population
    
```{r}
create_pop_chart(df_address = "data/processed/population/03_muncipality.csv")
``` 

Row
-------------------------------------
    
### People Per House
    
```{r}
create_per_house(df_address = "data/processed/population/03_muncipality.csv")
```
    
### Gender Distribution

```{r}
create_gen_chart(df_address = "data/processed/population/03_muncipality.csv")
```

